services: 
  details:
    build: .
    image: ghcr.io/jobbiez/bookinfo-details:prd
    ports:
      - "8081:8081"
    environment:
      ENABLE_EXTERNAL_BOOK_SERVICE: "true" 
      DO_NOT_ENCRYPT: "false" 
